name: Android CI - build apk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Supabase secrets into strings.xml
        run: |
          sed -i "s|__SUPABASE_URL__|${{ secrets.SUPABASE_URL }}|g" android-app/app/src/main/res/values/strings.xml
          sed -i "s|__SUPABASE_ANON_KEY__|${{ secrets.SUPABASE_ANON_KEY }}|g" android-app/app/src/main/res/values/strings.xml

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute for gradlew
        run: chmod +x android-app/gradlew || true

      - name: Build Debug APK
        working-directory: android-app
        run: |
          if [ ! -f ./gradlew ]; then
            sudo apt-get update && sudo apt-get install -y wget unzip
            wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip -O gradle.zip
            unzip gradle.zip -d /opt/gradle
            /opt/gradle/gradle-7.5.1/bin/gradle wrapper
          fi
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuto-app-debug-apk
          path: android-app/app/build/outputs/apk/debug/app-debug.apk
